# Netflix Movies & TV Shows – End-to-End Data Scienece Project
## Step 1: Data Inspection

In [137]:
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

BRONZE_RAW_DATA_PATH = os.getenv("BRONZE_RAW_DATA_PATH") or os.getenv("BROZE_RAW_DATA_PATH")
print("File Loaded!")

File Loaded!

In [138]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [139]:
df = pd.read_csv(BRONZE_RAW_DATA_PATH)
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [140]:
print("Last 5 rows of the dataset:")
df.tail()

Last 5 rows of the dataset:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [141]:
print("Size of the DataFrame:", df.size)
print("Shape of the DataFrame:", df.shape)
print("\nColumns in the DataFrame:", df.columns)

Size of the DataFrame: 105684
Shape of the DataFrame: (8807, 12)

Columns in the DataFrame: Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [142]:
print("Info of the DataFrame:")
df.info()

Info of the DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [143]:
print("Description of the DataFrame:")
df.describe()

Description of the DataFrame:

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [144]:
print("The number of Null Values : ", df.isnull().sum().sum())
print("The number of Duplicated Values : ", df.duplicated().sum())

The number of Null Values :  4307
The number of Duplicated Values :  0

In [145]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

## Step 2: Data Cleaning

In [146]:
# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print("Standardized column names:", df.columns)

Standardized column names: Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [147]:
# Check Missing Values
df.isnull().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

In [148]:
# Handle Missing Values
df.fillna({
    'director': 'Unknown',
    'cast': 'Unknown',
    'country': 'Unknown',
    'rating': 'Not Rated',
    'duration': '0 min',
    'listed_in': 'Unknown',
    'description': 'No Description'
}, inplace=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [149]:
df[['director', 'cast', 'country', 'rating', 'duration', 'listed_in', 'description']].isnull()

      director   cast  country  rating  duration  listed_in  description
0        False  False    False   False     False      False        False
1        False  False    False   False     False      False        False
2        False  False    False   False     False      False        False
3        False  False    False   False     False      False        False
4        False  False    False   False     False      False        False
...        ...    ...      ...     ...       ...        ...          ...
8802     False  False    False   False     False      False        False
8803     False  False    False   False     False      False        False
8804     False  False    False   False     False      False        False
8805     False  False    False   False     False      False        False
8806     False  False    False   False     False      False        False

[8807 rows x 7 columns]

In [150]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [151]:
# 1) Keep original date_added safe
# 2) Clean in a new column
# 3) Keep missing indicator
# 4) Impute with mid-year of release_year
# 5) Create business features

df["date_added_cleaned"] = pd.to_datetime(df["date_added"], errors="coerce")

df["date_added_missing"] = df["date_added_cleaned"].isna().astype(int)

release_year_date = pd.to_datetime(
    df["release_year"].astype(str) + "-07-01", errors="coerce"
)
df["date_added_cleaned"] = df["date_added_cleaned"].fillna(release_year_date)

# Keep the original column null-free for downstream checks
df["date_added"] = df["date_added_cleaned"]

df["year_added"] = df["date_added_cleaned"].dt.year
df["month_added"] = df["date_added_cleaned"].dt.month
df["day_added"] = df["date_added_cleaned"].dt.day

df["content_age_when_added"] = df["year_added"] - df["release_year"]

print("Missing in date_added_cleaned after imputation:", df["date_added_cleaned"].isna().sum())
print("Missing in date_added after replacement:", df["date_added"].isna().sum())
print("Rows originally missing date_added:", df["date_added_missing"].sum())

df[[
    "date_added",
    "date_added_cleaned",
    "date_added_missing",
    "release_year",
    "year_added",
    "month_added",
    "day_added",
    "content_age_when_added",
]].head()

Missing in date_added_cleaned after imputation: 0
Missing in date_added after replacement: 0
Rows originally missing date_added: 98

,date_added,date_added_cleaned,date_added_missing,release_year,year_added,month_added,day_added,content_age_when_added
0,2021-09-25,2021-09-25,0,2020,2021,9,25,1
1,2021-09-24,2021-09-24,0,2021,2021,9,24,0
2,2021-09-24,2021-09-24,0,2021,2021,9,24,0
3,2021-09-24,2021-09-24,0,2021,2021,9,24,0
4,2021-09-24,2021-09-24,0,2021,2021,9,24,0

In [152]:
# Final cleaning quality checks
text_cols = df.select_dtypes(include=["object", "string"]).columns
df[text_cols] = df[text_cols].apply(lambda col: col.str.strip())

duplicates_before = df.duplicated().sum()
df.drop_duplicates(inplace=True)
duplicates_after = df.duplicated().sum()

print("Total null values:", int(df.isnull().sum().sum()))
print("Duplicates before:", int(duplicates_before))
print("Duplicates after:", int(duplicates_after))
print("Current shape:", df.shape)

# Quick check
df[["date_added_missing", "year_added", "month_added", "day_added", "content_age_when_added"]].describe()

Total null values: 0
Duplicates before: 0
Duplicates after: 0
Current shape: (8807, 18)

,date_added_missing,year_added,month_added,day_added,content_age_when_added
count,8807.000000,8807.000000,8807.000000,8807.000000,8807.000000
mean,0.011128,2018.818894,6.657204,12.383218,4.638696
std,0.104904,1.890668,3.412481,9.900319,8.756986
min,0.000000,1967.000000,1.000000,1.000000,-3.000000
25%,0.000000,2018.000000,4.000000,1.000000,0.000000
50%,0.000000,2019.000000,7.000000,12.000000,1.000000
75%,0.000000,2020.000000,10.000000,20.000000,5.000000
max,1.000000,2021.000000,12.000000,31.000000,93.000000

In [153]:
print("Size of the DataFrame:", df.size)
print("Shape of the DataFrame:", df.shape)
print("\nColumns in the DataFrame:", df.columns)

Size of the DataFrame: 158526
Shape of the DataFrame: (8807, 18)

Columns in the DataFrame: Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'date_added_cleaned', 'date_added_missing', 'year_added', 'month_added',
       'day_added', 'content_age_when_added'],
      dtype='str')

In [154]:
df.isnull().sum()

show_id                   0
type                      0
title                     0
director                  0
cast                      0
country                   0
date_added                0
release_year              0
rating                    0
duration                  0
listed_in                 0
description               0
date_added_cleaned        0
date_added_missing        0
year_added                0
month_added               0
day_added                 0
content_age_when_added    0
dtype: int64

## Save this silver-level dataset

In [155]:
print("Size: ", df.shape)
df.head()

Size:  (8807, 18)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date_added_cleaned,date_added_missing,year_added,month_added,day_added,content_age_when_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021-09-25,0,2021,9,25,1
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021-09-24,0,2021,9,24,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021-09-24,0,2021,9,24,0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021-09-24,0,2021,9,24,0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021-09-24,0,2021,9,24,0

In [156]:
output_dir = os.path.join("..", "data", "silver")
os.makedirs(output_dir, exist_ok=True)

output_file = os.path.join(output_dir, "Silver_Cleaned_Netflix_Data.csv")
df.to_csv(output_file, index=False)
print(f"Silver Cleaned Netflix Data successfully saved!")

Silver Cleaned Netflix Data successfully saved!